name: responsive_size_util
description: A plugin for adapting screen and font size.
version: 0.0.1
author: jm lorenzo
homepage: 

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

